### ISSUE TITLE
Saving Displacement Fields at Original Input Dimensions in .nii.gz Format

### ISSUE THREAD

**Issue by junyuchen245** [uncbiag/uniGradICON#15]
Dear authors,

Great work, and thank you for making the code available as open source. I am interested in whether the authors could provide additional code for resampling the displacement to the original input dimensions, rather than the fixed 175x175x175, and for saving these in a .nii.gz format. Specifically, given your submissions to previous Learn2Reg challenges, it would be immensely helpful if you could share the code that saves the fields in a format compatible with Learn2Reg.

Thanks very much.
Junyu

**Comment by Pull2MAX** [comment]
woc ，陈哥

**Comment by lintian-a** [comment]
Hi @junyuchen245 ,

I appreciate your interest in uniGradICON! I have read the TransMorph and the survey on deep learning for medical image registration. They are very insightful!

After our paper is accepted, we plan to release all the code, including the evaluation script that saves the transformation in Learn2Reg compatible format. Stay tuned!

Before I can help, may I know which interface you use? Currently, we provide two interfaces. One is the Colab playground, where one can work directly with the input and output of the neural network and test some ideas. The other is the [ITK interface](https://github.com/uncbiag/uniGradICON?tab=readme-ov-file#easy-to-use-and-install), which accepts the nii.gz file as input and outputs the transformation and warped image with the appropriate metadata. The transform is saved in ITKCompositeTransform format.

**Comment by junyuchen245** [comment]
@lintian-a Thanks, Lin, for your kind words and quick reply! 

I installed the package from source, so it should be the ITK interface. I encountered issues while attempting to load the .hdf5 transformation file in Python, which led me to manually alter the `itk_wrapper.py` in the `icon_registration` package to save the displacements (phi_AB and phi_BA) as .nii.gz files. Although this worked, I noticed the files are sized at 175x175x175. I could resample these fields myself, but since I plan to use uniGradICON as a benchmark in this year’s Learn2Reg LUMIR challenge, I want to ensure I don’t compromise the integrity of your model. That’s why I’m reaching out for assistance. It’s great to hear that you'll be releasing all the code, and I’ll keep an eye out for that. Meanwhile, I encourage your team to join this year's LUMIR challenge. Also, I must mention, your group’s recent preprint on Inverse Consistency by Construction is very interesting and clever. Thanks for your outstanding contributions to the field.

Junyu

**Comment by lintian-a** [comment]
Thanks, Junyu!

I can help write a script to output the format compatible with the LUMIR challenge for benchmark uniGradICON on this task. 

The transformation format is slightly different across the previous Learn2Reg challenge tasks. On the website, each task has a section named "Submission Format," which describes how the transformation should be prepared and provides the evaluation script. If you could send me this information via email, I can write the script.
