### ISSUE TITLE
 Foundation model for registering 2D samples?

### ISSUE THREAD

**Issue by iyerkrithika21** [uncbiag/uniGradICON#17]
Do you have a foundation model (saved network weights) for registering 2D samples Or is there a way to predict the 2D  deformation fields using the current model?

**Comment by marcniethammer** [comment]
Sorry, no we currently don't. 

One option to try could be to simply replicate the 2D slice in the z direction to create a fake 3D volume. Though I am not sure how well uniGradICON would work in this case (as it has never seen such data). If you try it I would be curious to know if this works.

**Comment by HastingsGreer** [comment]
Hi! While we don't have a foundation model for 2-D, we have worked on making training a custom 2-D model as easy as possible. The example at https://icon.readthedocs.io/en/master/register_fives.html trains in a few minutes on a free tier colab notebook.
